### ISSUE TITLE
web3.eth.subscribe not working

### ISSUE THREAD

**Issue by LiorRabin** [decentraland/ethalarm#1]
Hello,

This tool looks awesome, tried to make it work for me but couldn't get the alerts.

See https://github.com/ethereum/web3.js/issues/1093

Any help appreciated :)

Thanks

**Comment by dafky2000** [comment]
I experienced a similar issue with a not fully synced Geth instance. Switched to Parity and it synced up quickly and then it worked. I am inclined to believe this wasn't an issue with Geth but with the fact it wasn't fully synced up.

Could you confirm that you are fully synced?

**Comment by LiorRabin** [comment]
@dafky2000 our Geth instance is fully synced

**Comment by LiorRabin** [comment]
ok, so I've solved the issue running:

`geth --rpc --rpccorsdomain="*" --ws --wsorigins="*" --wsaddr 0.0.0.0 --testnet --rpcaddr 0.0.0.0`

Note: need to set BOTH rpccorsdomain & wsorigins
